### ISSUE TITLE
DG chose Traitor but transformed to Wolf

### ISSUE THREAD

**Issue by renyhp** [parabola949/Werewolf#163]
Untransformed traitor was lynched (there were other living werewolves). DG had chosen them, and transformed, but became wolf instead of traitor.
I'm pretty sure it is not relevant, but on previous night the alpha wolf bit someone (who then correctly became wolf the following night).

**Comment by renyhp** [comment]
I don't know if it's related to this bug, but I just got another similar bug report: Alpha Wolf's DG transformed to normal wolf.

**Comment by ambravl** [comment]
Happened again, within the first 24 game hours. Untransformed traitor was smited during the first night. DG had chosen them, and didn't get any messages about transforming from the bot. There wasn't any conversion made by the alpha wolf, instead the drunk was eaten that night. The following day, DG was lynched, and the death message showed them as a wolf instead of a traitor (even though there were still wolves alive).

**Comment by parabola949** [comment]
@ambravl That's a really cool feature!

Kidding, I'll look into it
