### ISSUE TITLE
Amnesia mode in German puts out english wolf cub string

### ISSUE THREAD

**Issue by Olfi01** [parabola949/Werewolf#169]
It isn't even the Amnesia one, pls fix it.

**Comment by renyhp** [comment]
Our translator team is made up only by volunteers, and currently no one is taking care of the German Amnesia language file. If you want to, you are welcome to update it, you'll just need to ping me on Telegram :) otherwise, please be patient until someone else volunteers.
In any case, I'll close this issue, because, as I said in #87, unfortunately this has nothing to do with developers. A GitHub issue won't help langfiles issues to be solved; Werewolf Telegram chats are the best place to search for people who want to update langfiles, IMO (other than pinging me to volunteer, obviously ;) )
